### ISSUE TITLE
Explore space - time tradeoffs

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/bayesdesign#4]
The size of a problem that can be solved is currently limited by the memory size of the likelihood array tabulated over the full (features x params x designs) grid.

This issue is to explore ways to allow calculations of (at least) the EIG using smaller internal grids.

To enable trade offs, the main API change is that the user will provide a function to tabulate the likelihood on an arbitrary grid, rather than the pre-tabulated array itself, i.e.
```
def calculate_likelihood(features, designs, params):
  with GridStack(features, designs, params):
    likelihood = ...
    features.normalize(likelihood)
  return likelihood

designer = ExperimentDesigner(params, features, designs, calculate_likelihood)
```

**Comment by dkirkby** [comment]
The main feature of the calculation that we can take advantage of here is that we only integrate over the parameter and feature grids, so the calculation can be decomposed into sub-calculations each on a sub-grid of the design space.

In order to automate this decomposition, we need to know the total amount of array memory available. Should this be specified by the user, or can we determine a sensible default from the system configuration?

**Comment by ashandonay** [comment]
I think it would be more user-friendly if the memory available was determined using the system by default. There could be an optional argument for the user to specify, possibly as a percentage of the calculated available memory, in case they want to remain within some memory constraint.

**Comment by dkirkby** [comment]
I don't think there is a standard library that can do this, but the pip-installable [psutil package](https://github.com/giampaolo/psutil) works across platforms according to this [SO question](https://stackoverflow.com/a/22103295):
```python
import psutil

psutil.virtual_memory().total  # total physical memory in Bytes
```

**Comment by ashandonay** [comment]
I just created a branch called iterate_designs which includes an implementation of this concept. I tested it on both the location finding and sine wave problem and it seems to function correctly. The way it works is by first setting a memory constraint in MB using an ExperimentDesigner arg, then it calculates the required fractional decrease in memory for the likelihood, then it uses this fraction to determine how to split the design grid into smaller components. Then it loops through the design grid in the calculateEIG function and applies the output EIG to the corresponding sub-grid location in the full EIG output. I haven't yet adapted the other functions such as describe or get_posterior to work within this framework, but I just wanted to get this code on GitHub. In addition, my subgrid function in Grid.py doesn't currently work with design grid constraints due to how I split it up.

Here's a test example
```
designs = Grid(x_obs=np.linspace(0, L, 40), y_obs=np.linspace(0, L, 40))
features = Grid(s=np.linspace(np.log(0.08), np.log(1.5), 200))
params = Grid(l_x1=np.linspace(0, L, 75), l_y1=np.linspace(0, L, 75), b=0.1, m=1.0)

def calculate_likelihood(features, designs, params):
    sigma_s = 0.1 
    sq_two_norm = np.square(designs.x_obs - params.l_x1) + np.square(designs.y_obs - params.l_y1)
    sq_two_norm_inverse = 1/(params.m + sq_two_norm)
    s_mean = np.log(params.b + sq_two_norm_inverse)
    s_diff = features.s - s_mean
    likelihood = np.exp(-0.5 * (s_diff / sigma_s) ** 2)
    features.normalize(likelihood)
    return likelihood

designer = ExperimentDesigner(params, features, designs, calculate_likelihood, mem=2000)

prior = np.ones(params.shape)
params.normalize(prior)

designer.calculateEIG(prior)
```
